# Generated by Django 4.0.6 on 2022-07-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
