# Generated by Django 4.0.6 on 2022-07-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_invoice_returnproducts_replaceproducts_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
