# Generated by Django 4.0.6 on 2022-07-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PLACED', 'PLACED'), ('FAIL', 'FAIL'), ('CANCELED', 'CANCELED')], default='PLACED', max_length=20),
        ),
    ]
