# Generated by Django 4.0.6 on 2022-07-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_status',
            field=models.CharField(choices=[('Not Packed', 'Not Packed'), ('Ready For Shipment', 'Ready For Shipment'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Not Packed', max_length=20),
        ),
    ]
