# Generated by Django 4.0.6 on 2022-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_rename_order_status_invoice_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Not Packed', 'Not Packed'), ('Ready For Shipment', 'Ready For Shipment'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned'), ('Replaced', 'Replaced')], default='Not Packed', max_length=20),
        ),
    ]
